version: '3.8'

services:
  php:
    build: .docker/php
    container_name: backend_agungkusaericom
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
    networks:
      - networklocal

  nginx:
    image: nginx:latest
    container_name: agungkusaericom
    ports:
      - "9001:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - networklocal

networks:
  networklocal:
    external: true
