services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        # ports:
        #     - 5173:5173
        volumes:
            - .:/var/www:cached
        networks:
            - local-network
        env_file:
            - .env.docker
    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 9002:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - local-network


networks:
    local-network:
        driver: bridge